import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }) {

  const cookieStore = cookies()
  const supabase = createServerComponentClient({ cookies: () => cookieStore })

  const {
    data: { user },
  } = await supabase.auth.getUser()
  return (
    <html lang="en">
      {user &&
        <body className={`${inter.className} flex w-screen`}>
          <Navigation />
          <div className="absolute top-0 right-0 flex justify-center pt-10 w-5/6">{children}</div>
        </body>
      }
      { !user &&
      <body className={`${inter.className} flex w-screen`}>{children}</body>
      }
    </html>
  );
}
